// Mock data for Rivyuu-Connect frontend demo

export const MOCK_USERS = [
  {
    id: 'u0',
    name: 'Sathiyanarayanan (Admin)',
    username: 'sathiyanarayanan',
    email: 'sathyaviji2008@gmail.com',
    avatar: null,
    initials: 'SA',
    bio: 'Platform Creator & System Admin. Overseeing trust verification and reviewer community.',
    location: 'Chennai, India',
    joinedAt: '2024-01-01',
    trustScore: 98,
    reviewCount: 250,
    helpfulVotes: 3420,
    followers: 1250,
    following: 120,
    badges: ['verified', 'top-reviewer', 'ai-detected-trustworthy', 'early-adopter', 'community-champion'],
    level: 'Diamond',
    xp: 9950,
    nextLevelXp: 10000,
    isVerified: true,
    role: 'ADMIN',
  },
  {
    id: 'u1',
    name: 'Arjun Mehta',
    username: 'arjunm',
    email: 'arjun@example.com',
    avatar: null,
    initials: 'AM',
    bio: 'Tech enthusiast & serial reviewer. Helping businesses improve through honest feedback.',
    location: 'Bengaluru, India',
    joinedAt: '2024-01-15',
    trustScore: 92,
    reviewCount: 147,
    helpfulVotes: 1238,
    followers: 342,
    following: 89,
    badges: ['verified', 'top-reviewer', 'ai-detected-trustworthy', 'early-adopter', 'community-champion'],
    level: 'Diamond',
    xp: 9850,
    nextLevelXp: 10000,
    isVerified: true,
    role: 'USER',
  },
  {
    id: 'u2',
    name: 'Priya Sharma',
    username: 'priyasharma',
    email: 'priya@example.com',
    avatar: null,
    initials: 'PS',
    bio: 'Food blogger & restaurant critic. Honest reviews, every time.',
    location: 'Mumbai, India',
    joinedAt: '2024-03-20',
    trustScore: 87,
    reviewCount: 89,
    helpfulVotes: 654,
    followers: 201,
    following: 55,
    badges: ['verified', 'foodie-expert', 'ai-detected-trustworthy'],
    level: 'Gold',
    xp: 5620,
    nextLevelXp: 7000,
    isVerified: true,
  },
  {
    id: 'u3',
    name: 'Rahul Nair',
    username: 'rahulnair',
    email: 'rahul@example.com',
    avatar: null,
    initials: 'RN',
    bio: 'Product manager by day, reviewer by night.',
    location: 'Hyderabad, India',
    joinedAt: '2024-05-10',
    trustScore: 78,
    reviewCount: 52,
    helpfulVotes: 312,
    followers: 98,
    following: 72,
    badges: ['verified', 'rising-star'],
    level: 'Silver',
    xp: 3200,
    nextLevelXp: 5000,
    isVerified: false,
  },
  {
    id: 'u4',
    name: 'Sneha Patel',
    username: 'snehap',
    email: 'sneha@example.com',
    avatar: null,
    initials: 'SP',
    bio: 'Travel lover and lifestyle reviewer.',
    location: 'Ahmedabad, India',
    joinedAt: '2024-07-01',
    trustScore: 71,
    reviewCount: 33,
    helpfulVotes: 178,
    followers: 65,
    following: 40,
    badges: ['early-adopter'],
    level: 'Bronze',
    xp: 1800,
    nextLevelXp: 3000,
    isVerified: false,
  },
  {
    id: 'u5',
    name: 'Karan Singh',
    username: 'karansingh',
    email: 'karan@example.com',
    avatar: null,
    initials: 'KS',
    bio: 'Fitness freak and supplement reviewer.',
    location: 'Delhi, India',
    joinedAt: '2024-02-28',
    trustScore: 85,
    reviewCount: 76,
    helpfulVotes: 489,
    followers: 167,
    following: 61,
    badges: ['verified', 'health-expert', 'ai-detected-trustworthy'],
    level: 'Gold',
    xp: 4900,
    nextLevelXp: 7000,
    isVerified: true,
  },
];

export const MOCK_BUSINESSES = [
  {
    id: 'b1',
    name: 'Zomato',
    category: 'Food Delivery',
    logo: '🍕',
    rating: 4.2,
    reviewCount: 12847,
    trustScore: 88,
    verified: true,
  },
  {
    id: 'b2',
    name: 'Swiggy',
    category: 'Food Delivery',
    logo: '🛵',
    rating: 4.0,
    reviewCount: 9523,
    trustScore: 84,
    verified: true,
  },
  {
    id: 'b3',
    name: 'Flipkart',
    category: 'E-Commerce',
    logo: '🛒',
    rating: 3.8,
    reviewCount: 45123,
    trustScore: 79,
    verified: true,
  },
  {
    id: 'b4',
    name: 'Ola',
    category: 'Ride Sharing',
    logo: '🚗',
    rating: 3.6,
    reviewCount: 28456,
    trustScore: 72,
    verified: true,
  },
  {
    id: 'b5',
    name: 'Nykaa',
    category: 'Beauty & Wellness',
    logo: '💄',
    rating: 4.5,
    reviewCount: 7832,
    trustScore: 91,
    verified: true,
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'r1',
    userId: 'u1',
    businessId: 'b1',
    businessName: 'Zomato',
    businessLogo: '🍕',
    rating: 4,
    title: 'Great delivery speed, packaging needs improvement',
    content: 'Ordered from Zomato multiple times this month. Delivery is consistently fast — usually under 30 minutes. The app interface is clean and easy to use. However, I\'ve noticed that packaging for liquid items like soups and beverages is often inadequate, leading to spills. Would appreciate better insulation for hot items too.',
    aiSentiment: 'positive',
    aiScore: 72,
    aiLabel: 'Mostly Constructive',
    helpful: 89,
    notHelpful: 4,
    verified: true,
    timestamp: '2025-07-20T14:32:00Z',
    tags: ['delivery', 'packaging', 'food'],
    images: [],
    response: {
      text: 'Thank you for your honest feedback! We\'re actively working on improving our packaging standards.',
      timestamp: '2025-07-21T09:00:00Z',
    },
  },
  {
    id: 'r2',
    userId: 'u2',
    businessId: 'b5',
    businessName: 'Nykaa',
    businessLogo: '💄',
    rating: 5,
    title: "Absolutely love Nykaa's product range!",
    content: 'Nykaa has completely transformed my beauty shopping experience. The product selection is incredible — from drugstore to luxury brands, everything is available. Delivery is always on time and packaging is premium. Customer service resolved my return issue within 24 hours. Highly recommend for all beauty enthusiasts!',
    aiSentiment: 'positive',
    aiScore: 95,
    aiLabel: 'Highly Positive & Authentic',
    helpful: 156,
    notHelpful: 2,
    verified: true,
    timestamp: '2025-07-18T10:15:00Z',
    tags: ['beauty', 'delivery', 'customer-service'],
    images: [],
    response: null,
  },
  {
    id: 'r3',
    userId: 'u3',
    businessId: 'b3',
    businessName: 'Flipkart',
    businessLogo: '🛒',
    rating: 3,
    title: 'Mixed experience — great products, terrible returns',
    content: 'Product quality and pricing on Flipkart is generally good. However, the returns process is a nightmare. Waited 2 weeks for a return pickup that never happened. Had to escalate multiple times. The app crashes frequently on my Android device. The "Flipkart Assured" label doesn\'t always mean what it promises.',
    aiSentiment: 'mixed',
    aiScore: 45,
    aiLabel: 'Mixed — Credible Issues Identified',
    helpful: 234,
    notHelpful: 12,
    verified: true,
    timestamp: '2025-07-15T16:45:00Z',
    tags: ['returns', 'app', 'customer-service'],
    images: [],
    response: {
      text: 'We sincerely apologize for the inconvenience. Our team is reaching out to resolve this immediately.',
      timestamp: '2025-07-16T11:30:00Z',
    },
  },
  {
    id: 'r4',
    userId: 'u5',
    businessId: 'b2',
    businessName: 'Swiggy',
    businessLogo: '🛵',
    rating: 4,
    title: 'Swiggy Instamart is a game changer!',
    content: 'Swiggy Instamart delivers groceries in under 15 minutes in my area. The quality is fresh and prices are competitive with local stores. The app has improved significantly. My only gripe is occasional out-of-stock items not being updated in real time, leading to order cancellations.',
    aiSentiment: 'positive',
    aiScore: 82,
    aiLabel: 'Positive with Valid Concerns',
    helpful: 67,
    notHelpful: 3,
    verified: false,
    timestamp: '2025-07-22T08:20:00Z',
    tags: ['grocery', 'speed', 'app'],
    images: [],
    response: null,
  },
  {
    id: 'r5',
    userId: 'u4',
    businessId: 'b4',
    businessName: 'Ola',
    businessLogo: '🚗',
    rating: 2,
    title: 'Driver cancellations are extremely frustrating',
    content: 'I use Ola daily for commuting. The biggest problem is drivers cancelling rides after accepting — happened 4 times last week alone. This wastes significant time. Pricing during peak hours has increased dramatically. The new Ola Electric bikes look promising but the cab service quality has declined noticeably.',
    aiSentiment: 'negative',
    aiScore: 28,
    aiLabel: 'Negative — Specific Grievances',
    helpful: 312,
    notHelpful: 18,
    verified: true,
    timestamp: '2025-07-19T07:55:00Z',
    tags: ['cancellation', 'pricing', 'reliability'],
    images: [],
    response: null,
  },
  {
    id: 'r6',
    userId: 'u1',
    businessId: 'b3',
    businessName: 'Flipkart',
    businessLogo: '🛒',
    rating: 5,
    title: 'Big Billion Days sale delivered amazing value',
    content: 'Bought a laptop and wireless earphones during the Big Billion Days sale. Both items arrived 2 days ahead of schedule and in perfect condition. The deals were genuine — I tracked prices beforehand. EMI options on Flipkart are the best in the market. Zero-cost EMI on SBI cards is a great feature.',
    aiSentiment: 'positive',
    aiScore: 90,
    aiLabel: 'Highly Authentic Positive Review',
    helpful: 145,
    notHelpful: 5,
    verified: true,
    timestamp: '2025-07-10T13:00:00Z',
    tags: ['sale', 'electronics', 'value'],
    images: [],
    response: null,
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n1',
    type: 'helpful_vote',
    message: 'Priya Sharma found your review of Zomato helpful',
    avatar: 'PS',
    timestamp: '2025-07-26T07:30:00Z',
    read: false,
    link: '/review/r1',
  },
  {
    id: 'n2',
    type: 'badge_earned',
    message: 'You earned the "Community Champion" badge! 🏆',
    avatar: '🏆',
    timestamp: '2025-07-25T14:20:00Z',
    read: false,
    link: '/profile',
  },
  {
    id: 'n3',
    type: 'business_response',
    message: 'Flipkart responded to your review',
    avatar: '🛒',
    timestamp: '2025-07-24T09:15:00Z',
    read: false,
    link: '/review/r3',
  },
  {
    id: 'n4',
    type: 'follower',
    message: 'Karan Singh started following you',
    avatar: 'KS',
    timestamp: '2025-07-23T16:45:00Z',
    read: true,
    link: '/profile/karansingh',
  },
  {
    id: 'n5',
    type: 'trust_score',
    message: 'Your Trust Score increased to 92! Keep it up 🚀',
    avatar: '⭐',
    timestamp: '2025-07-22T11:00:00Z',
    read: true,
    link: '/profile',
  },
  {
    id: 'n6',
    type: 'helpful_vote',
    message: '234 people found your Flipkart review helpful',
    avatar: '👍',
    timestamp: '2025-07-21T08:30:00Z',
    read: true,
    link: '/review/r3',
  },
];

export const LEADERBOARD_DATA = [
  { rank: 1, user: MOCK_USERS[0], change: 0, weeklyReviews: 12, streak: 47 },
  { rank: 2, user: MOCK_USERS[4], change: 1, weeklyReviews: 9, streak: 34 },
  { rank: 3, user: MOCK_USERS[1], change: -1, weeklyReviews: 8, streak: 28 },
  { rank: 4, user: MOCK_USERS[2], change: 2, weeklyReviews: 6, streak: 15 },
  { rank: 5, user: MOCK_USERS[3], change: 0, weeklyReviews: 4, streak: 8 },
];

export const BADGES_CATALOG = [
  { id: 'verified', label: 'Verified Reviewer', icon: '✅', description: 'Identity verified via official documents', color: '#10b981', rarity: 'Common' },
  { id: 'top-reviewer', label: 'Top Reviewer', icon: '🏆', description: 'Ranked in top 1% of reviewers', color: '#f59e0b', rarity: 'Legendary' },
  { id: 'ai-detected-trustworthy', label: 'AI Trustworthy', icon: '🤖', description: 'AI analysis confirms authentic review patterns', color: '#7c3aed', rarity: 'Rare' },
  { id: 'early-adopter', label: 'Early Adopter', icon: '🚀', description: 'Among first 1000 users on the platform', color: '#06b6d4', rarity: 'Rare' },
  { id: 'community-champion', label: 'Community Champion', icon: '👑', description: 'Exceptional contributions to the community', color: '#f59e0b', rarity: 'Epic' },
  { id: 'foodie-expert', label: 'Foodie Expert', icon: '🍽️', description: '50+ verified food & restaurant reviews', color: '#ef4444', rarity: 'Uncommon' },
  { id: 'rising-star', label: 'Rising Star', icon: '⭐', description: 'Fast-growing reviewer with high engagement', color: '#fbbf24', rarity: 'Uncommon' },
  { id: 'health-expert', label: 'Health Expert', icon: '💪', description: '30+ verified health & fitness reviews', color: '#10b981', rarity: 'Uncommon' },
];

export const TRUST_GRAPH_DATA = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
  scores: [68, 72, 75, 79, 83, 88, 92],
  reviews: [8, 15, 22, 31, 45, 67, 89],
};

export const BUSINESS_ANALYTICS = {
  totalReviews: 12847,
  averageRating: 4.2,
  trustScore: 88,
  responseRate: 76,
  monthlyData: [
    { month: 'Jan', reviews: 820, rating: 4.0, sentiment: 72 },
    { month: 'Feb', reviews: 940, rating: 4.1, sentiment: 75 },
    { month: 'Mar', reviews: 1100, rating: 4.0, sentiment: 70 },
    { month: 'Apr', reviews: 1350, rating: 4.2, sentiment: 78 },
    { month: 'May', reviews: 1580, rating: 4.3, sentiment: 82 },
    { month: 'Jun', reviews: 1820, rating: 4.2, sentiment: 80 },
    { month: 'Jul', reviews: 2100, rating: 4.4, sentiment: 85 },
  ],
  sentimentBreakdown: { positive: 68, neutral: 21, negative: 11 },
  ratingDistribution: { 5: 38, 4: 32, 3: 16, 2: 8, 1: 6 },
  topCategories: [
    { name: 'Delivery Speed', score: 88 },
    { name: 'App Experience', score: 82 },
    { name: 'Food Quality', score: 79 },
    { name: 'Customer Support', score: 71 },
    { name: 'Packaging', score: 65 },
  ],
};
